name: Bug report
description: Report un bug
title: '[Bug]: '
labels:
  - 'bug'
  - 'triage'
body:
  - type: input
    id: pseudo
    attributes:
      label: Pseudo (Pseudo#0000) => Identifiant (365844280209702913)
    validations:
      required: true
  - type: input
    id: server-id
    attributes:
      label: Server Id
    validations:
      required: true
  - type: input
    id: command-name
    attributes:
      label: Commande
      description: Nom de la commande utilisée
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est-il passé ?
      description: Dites-nous ce qui est arrivé
    validations:
      required: true
  - type: textarea
    id: what-should-happened
    attributes:
      label: "Qu'aurait-il dû arriver ?"
      description: Dites-nous ce qui aurait dû arriver
