name: Bug report
description: Report un bug
title: '[Bug]: '
labels:
  - 'bug'
  - 'triage'
body:
  - type: input
    id: pseudo
    atributes:
      label: Pseudo
    validations:
      required: true